---
- name: Install and configure httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: latest
      notify: restart httpd

    - name: Change index.html to say hello world
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 664
      notify: restart httpd

    - name: Ensure httpd service is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
