---
- name: Install and configure httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd

    - name: Change index.html to say hello world

    - name: Ensure httpd service is started and enabled

  handlers:
    - name: restart httpd
