---
- name: Install and configure httpd
  hosts: all
  become: true

  tasks:
    - name: Install httpd
      ansible.builtin.package:
        name: httpd
        state: present


    - name: Change index.html to say hello world
      ansible.builtin.copy:
        content: Hello World!
        dest: /var/www/html/index.html
      notify: restart httpd

    - name: Ensure httpd service is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
