---
- name: Configure WinRM to be STIG Compliant
  hosts: os_windows
  gather_facts: false
  vars:
    ps_script: undef
  
  tasks:
    - name: Run PowerShell
      ansible.windows.win_powershell:
        script: | 
          {{ ps_script }}
      register: ps_output

    - debug:
        msg: "{{ ps_output.output }}"
      
    - name: CAT 1 Ensure Windows Remote Management (WinRM) does not use Basic authentication on Windows Server 2019
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client
        state: present
        value: AllowBasic
        data: 0
        datatype: dword
